In [1]:
from bs4 import BeautifulSoup
from urllib.request import urlopen
from urllib import parse as urlparse
from dateutil.parser import parse
import pandas as pd

parks_list = ['Iona National Park','Quiçama National Park', 'Cameia National Park', 'Mosi-oa-Tunya National Park', 'Daan Viljoen Game Reserve', 'Karoline National Park']
converter = lambda x: x.replace(' ', '_')
parks = list(map(converter, parks_list))

data = [] #cria um array vazio para servir de base para o Data Frame

for park in parks:
    BASE = 'https://en.wikipedia.org/w/index.php?title='+ urlparse.quote(park) +'&action=info'  
  
    park_url = urlopen(BASE)
    pk = BeautifulSoup(park_url, 'html.parser')
    tables = pk.find_all('table')
    interruptor = False
    for table in tables:
        if len(table) >1:
            rows = table.find_all('tr')
            for row in rows[0:]:
                cells = row.find_all('td')
                if (cells[0].text.strip())=='Date of page creation':
                    #print(parse(cells[1].text.strip()).date())
                    infos_pk = {
                        'nm_pk': park, #salva o nome do parque analisado
                        'dt_create_pg': cells[1].text.strip(), #parse(cells[1].text.strip()).date(),
                        'teste': cells[0].text.strip() #salva a data de criação da página
                    } #cria um dicionário que será adicionado ao array vazio
                    data.append(infos_pk) #adiciona o novo dicionário "info_pk" ao array "data"
                    interruptor = True 
    if not interruptor:
        infos_pk = {
            'nm_pk': park,
            'dt_create_pg': 'não tem wikipedia'
        }
        data.append(infos_pk)


df = pd.DataFrame(data) #transforma o array "data" em um Data Frame
df

                         nm_pk             dt_create_pg                  teste
0           Iona_National_Park      06:46, 14 June 2006  Date of page creation
1        Quiçama_National_Park      18:26, 11 June 2008  Date of page creation
2         Cameia_National_Park      18:48, 11 June 2006  Date of page creation
3  Mosi-oa-Tunya_National_Park  14:53, 1 September 2005  Date of page creation
4    Daan_Viljoen_Game_Reserve       21:59, 19 May 2007  Date of page creation
5       Karoline_National_Park        não tem wikipedia                    NaN

In [ ]:
from bs4 import BeautifulSoup
from urllib.request import urlopen
from urllib import parse as urlparse
from dateutil.parser import parse
import pandas as pd

parks_list = ['Iona National Park','Quiçama National Park', 'Cameia National Park', 'Mosi-oa-Tunya National Park', 'Daan Viljoen Game Reserve', 'Karoline National Park']
converter = lambda x: x.replace(' ', '_')
parks = list(map(converter, parks_list))

data = [] #cria um array vazio para servir de base para o Data Frame

for park in parks:
    BASE = 'https://en.wikipedia.org/w/index.php?title='+ urlparse.quote(park) +'&action=info'  
  
    park_url = urlopen(BASE)
    pk = BeautifulSoup(park_url, 'html.parser')
    tables = pk.find_all('table')
    print(tables[0])

In [10]:
from bs4 import BeautifulSoup
from time import sleep
from urllib.request import urlopen
from urllib import parse as urlparse
from dateutil.parser import parse
import pandas as pd

parks_list = ['Iona National Park','Quiçama National Park', 'Cameia National Park', 'Mosi-oa-Tunya National Park', 'Daan Viljoen Game Reserve', 'Karoline National Park']
converter = lambda x: x.replace(' ', '_')
parks = list(map(converter, parks_list))

data = [] #cria um array vazio para servir de base para o Data Frame

for park in parks:
    print(f"Buscando dados para o park {park}")
    BASE = 'https://en.wikipedia.org/w/index.php?title='+ urlparse.quote(park) +'&action=info'  
  
    park_url = urlopen(BASE)
    pk = BeautifulSoup(park_url, 'html.parser')
    tables = pk.find_all('table')
    infos_pk = {'nm_pk': park}
    for table in tables:
        if len(table) >1:
            rows = table.find_all('tr')
            for row in rows[0:]:
                cells = row.find_all('td')
                if (cells[0].text.strip())=='Date of page creation':
                    #print(parse(cells[1].text.strip()).date())
                    dic_1 = {
                        'dt_create_pg': cells[1].text.strip() #salva a data de criação da página
                    } #cria um dicionário que será adicionado ao array vazio
                    infos_pk.update(dic_1)
                if (cells[0].text.strip())=='Wikidata item ID':
                    dic_2 = {
                        'wikidata_id': cells[1].text.strip() #
                    } 
                    infos_pk.update(dic_2)
                if (cells[0].text.strip())=='Central description':
                    dic_3 = {
                        'dsc_central': cells[1].text.strip() 
                    } 
                    infos_pk.update(dic_3)
        data.append(infos_pk)
    
    sleep(3)


df = pd.DataFrame(data) #transforma o array "data" em um Data Frame
df

Buscando dados para o park Iona_National_Park
Buscando dados para o park Quiçama_National_Park
Buscando dados para o park Cameia_National_Park
Buscando dados para o park Mosi-oa-Tunya_National_Park
Buscando dados para o park Daan_Viljoen_Game_Reserve
Buscando dados para o park Karoline_National_Park

,nm_pk,wikidata_id,dsc_central,dt_create_pg
0,Iona_National_Park,Q3123422,Natural protection zone in the province of Nam...,"06:46, 14 June 2006"
1,Iona_National_Park,Q3123422,Natural protection zone in the province of Nam...,"06:46, 14 June 2006"
2,Iona_National_Park,Q3123422,Natural protection zone in the province of Nam...,"06:46, 14 June 2006"
3,Iona_National_Park,Q3123422,Natural protection zone in the province of Nam...,"06:46, 14 June 2006"
4,Quiçama_National_Park,Q3179197,national park in Angola,"18:26, 11 June 2008"
5,Quiçama_National_Park,Q3179197,national park in Angola,"18:26, 11 June 2008"
6,Quiçama_National_Park,Q3179197,national park in Angola,"18:26, 11 June 2008"
7,Quiçama_National_Park,Q3179197,national park in Angola,"18:26, 11 June 2008"
8,Cameia_National_Park,Q3123444,"national park in Moxico province, Angola","18:48, 11 June 2006"
9,Cameia_National_Park,Q3123444,"national park in Moxico province, Angola","18:48, 11 June 2006"
10,Cameia_National_Park,Q3123444,"national park in Moxico province, Angola","18:48, 11 June 2006"
11,Cameia_National_Park,Q3123444,"national park in Moxico province, Angola","18:48, 11 June 2006"
12,Mosi-oa-Tunya_National_Park,Q1323548,national park of Zambia,"14:53, 1 September 2005"
13,Mosi-oa-Tunya_National_Park,Q1323548,national park of Zambia,"14:53, 1 September 2005"
14,Mosi-oa-Tunya_National_Park,Q1323548,national park of Zambia,"14:53, 1 September 2005"
15,Mosi-oa-Tunya_National_Park,Q1323548,national park of Zambia,"14:53, 1 September 2005"
16,Daan_Viljoen_Game_Reserve,Q1156470,NaN,"21:59, 19 May 2007"
17,Daan_Viljoen_Game_Reserve,Q1156470,NaN,"21:59, 19 May 2007"
18,Daan_Viljoen_Game_Reserve,Q1156470,NaN,"21:59, 19 May 2007"
19,Daan_Viljoen_Game_Reserve,Q1156470,NaN,"21:59, 19 May 2007"
20,Karoline_National_Park,NaN,NaN,NaN
21,Karoline_National_Park,NaN,NaN,NaN